Create db
AHP15/db-based-on-diagram pull request #1
Opened 2023-01-24 15:39 UTC by Abdessittir

In this PR I added the following:

 - Create a file named `schema_based_on_diagram.sql`
 - Add FK indexes

2023-01-24 16:55 UTC, Munsa1 requested changes
Hi @Abdessittir  @z4cope , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Highlights


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- x
- y
- z

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-24 16:55 UTC, Munsa1 commented on schema_based_on_diagram.sql
> +  medical_history_id INT REFERENCES medical_histories(id),
- [ ] It is a requirement that all `"join table"` for the many-to-many relastionships is created, even if they are not showed on the diagram. KIndly create a table between medical_histories and treatments.
![image](https://user-images.githubusercontent.com/81932478/214354859-d35cd226-4d52-42a6-983b-8713252b68b4.png)

2023-01-24 16:55 UTC, Munsa1 commented on schema_based_on_diagram.sql
> +);
- [ ] It is a requirement that all FOREIGN KEYS have indexes created according to how you named your tables. Checkout the code snippet below.
![image](https://user-images.githubusercontent.com/81932478/214355728-c75fcf43-a435-458b-b300-7153a6e2deb9.png)

2023-01-25 08:37 UTC, jerryowusu approved these changes
Hi @Abdessittir , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 


![good job](https://user-images.githubusercontent.com/65233860/214516385-3a026a05-4d42-4d76-8791-a082a99bf632.gif)

## Highlights
Used gitflow :heavy_check_mark: 
Great effort so far :heavy_check_mark: 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-25 08:42 UTC, merged